//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Beadandó
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorsoltak
    {
        public int SorsoltId { get; set; }
        public string SorsoltNév { get; set; }
        public string SorsoltEmail_cím { get; set; }
    }
}
